<?php

namespace Parsingcorner\CronManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Parsingcorner\CronManagerBundle\Entity\TblCronTask;

/**
 * TblCronTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblCronTaskRepository extends EntityRepository
{
    /**
     * @return TblCronTask[]
     */
    public function getActiveCronTasks()
    {
        $this->clear();
        return $this->findBy(array(
            'active' => true
        ));
    }
}
